[package]
name = "object-detection-stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["macros"] }
bytes = "1.4.0"
console-subscriber = "0.1.10"
flume = "0.10.14"
futures-util = "0.3.28"
serde = { version = "1.0.183", features = ["derive"] }
tokio = { version = "1.31.0", features = ["full", "rt-multi-thread", "tracing"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
uuid = { version = "1.4.1", features = ["v4"] }
